Repository twgroupcl/simple-gestion, pull requests merged in 2020-12, with the labels that each got.

#360 POS: Try to reload cart list if it is losed
  app/Http/Livewire/Pos/Cart/Cart.php
  resources/views/livewire/pos/cart/cart.blade.php
Labels: bug

#362 POS: Discount and fix product cart list
  app/Http/Livewire/Pos/Cart/Cart.php
  resources/views/livewire/pos/cart/cart.blade.php
Labels: bug, enhancement

#365 Pos integrate
  app/Http/Controllers/Admin/ManageInvoiceCrudController.php
  app/Http/Livewire/Pos/Customer/CustomerView.php
  app/Http/Livewire/Pos/Pos.php
  app/Http/Livewire/Pos/Product.php
  composer.json
  composer.lock
  public/img/no-image-64.png
  public/img/no-image-96.png
  public/packages/backpack/base/css/bundle.css
  resources/views/livewire/pos/cart/cart.blade.php
  resources/views/livewire/pos/customer/customer-view.blade.php
  resources/views/livewire/pos/partials/cart.blade.php
  resources/views/livewire/pos/partials/confirm-payment.blade.php
  resources/views/livewire/pos/partials/final-payment.blade.php
  resources/views/livewire/pos/partials/payment.blade.php
  resources/views/livewire/pos/partials/sale-box.blade.php
  resources/views/livewire/pos/pos.blade copy.php
  resources/views/livewire/pos/pos.blade.php
  resources/views/livewire/pos/product.blade.php
  resources/views/livewire/pos/report/pos-report-view.blade.php
  storage/framework/laravel-excel/.gitignore
Labels: enhancement

#367 Pos: fixes and send email
  app/Http/Livewire/Pos/Pos.php
  app/Mail/PosBill.php
  app/Mail/templates.json
  public/packages/backpack/base/css/bundle.css
  resources/views/livewire/pos/customer/customer-view.blade.php
  resources/views/livewire/pos/list-products.blade.php
  resources/views/livewire/pos/partials/cart.blade.php
  resources/views/livewire/pos/partials/final-payment.blade.php
  resources/views/livewire/pos/partials/payment.blade.php
  resources/views/livewire/pos/partials/sale-box.blade.php
  resources/views/livewire/pos/pos.blade.php
  resources/views/livewire/pos/product.blade.php
  resources/views/pos/index.blade.php
  resources/views/vendor/maileclipse/templates/invoice.blade.php
  resources/views/vendor/maileclipse/templates/invoice_plain_text.blade.php
Labels: bug, enhancement

#372 POS: tip and fixes
  app/Http/Livewire/Pos/Pos.php
  app/Mail/PosBill.php
  resources/views/livewire/pos/partials/cart.blade.php
  resources/views/livewire/pos/partials/final-payment.blade.php
  resources/views/livewire/pos/partials/payment.blade.php
  resources/views/livewire/pos/pos.blade copy.php
  resources/views/livewire/pos/pos.blade.php
  resources/views/livewire/pos/report/pos-report-view.blade.php
Labels: bug, enhancement
