Repository twgroupcl/simple-gestion, pull requests merged in 2020-11, with the labels that each got.

#156 Charts: Fix chart queries where are sold
  app/Models/Order.php
  app/Models/OrderItem.php
Labels: bug

#157 Profile: Download report button in order list
  resources/views/customer/order.blade.php
  resources/views/order/pdf_order.blade.php
Labels: enhancement

#218 Customer support: Fixes and filters
  app/Http/Controllers/Admin/CustomerSupportCrudController.php
  app/Http/Requests/CustomerSupportRequest.php
  app/Http/Requests/Frontend/CustomerSupportRequest.php
Labels: bug, enhancement

#219 fix weird error with non numeric sku
  app/Services/BulkUpload/BulkUploadBooksService.php
Labels: bug

#238 Customer support: Send Mails
  app/Http/Controllers/Frontend/CustomerController.php
  app/Mail/CustomerSupport.php
  app/Mail/templates.json
  resources/views/vendor/maileclipse/templates/customerSupport.blade.php
  resources/views/vendor/maileclipse/templates/customerSupport_plain_text.blade.php
Labels: enhancement

#243 fix filsa admin rol
  app/Http/Controllers/Admin/CommuneShippingMethodCrudController.php
  app/Http/Controllers/Admin/ProductCrudController.php
Labels: bug

#256 Fix mail cc to use settings admin emails
  app/Http/Controllers/Frontend/CustomerController.php
  app/Mail/CustomerSupport.php
Labels: enhancement

#252 Fix trait namespaces
  app/Http/Controllers/Admin/CustomerCrudController.php
  app/Http/Controllers/Admin/SellerCrudController.php
  app/Models/Customer.php
  app/Models/ProductCategory.php
  app/Models/Seller.php
  app/Traits/CustomAttributeRelations.php
  app/Traits/HasCustomAttributes.php
Labels: bug

#255 Customer support contigopyme
  app/Http/Controllers/Admin/CustomerSupportCrudController.php
  app/Http/Controllers/Frontend/CustomerController.php
  app/Http/Requests/CustomerSupportRequest.php
  app/Http/Requests/Frontend/CustomerSupportRequest.php
  app/Mail/CustomerSupport.php
  app/Mail/templates.json
  app/Models/CustomerSupport.php
  app/Models/CustomerSupportHistory.php
  database/migrations/2020_11_19_094033_create_customer_support_table.php
  database/migrations/2020_11_19_101332_create_customer_support_history_table.php
  resources/views/customer/support.blade.php
  resources/views/layouts/footer/menu.blade.php
  resources/views/livewire/support/customer-support-backpack.blade.php
  resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
  resources/views/vendor/maileclipse/templates/customerSupport.blade.php
  resources/views/vendor/maileclipse/templates/customerSupport_plain_text.blade.php
  routes/backpack/custom.php
  routes/web.php
Labels: enhancement

#275 Filsa hotfix bulk upload with decimals
  app/Models/Product.php
  app/Services/BulkUpload/BulkUploadBooksService.php
Labels: bug
