Repository twgroupcl/simple-gestion, pull requests merged in 2020-10, with the labels that each got.

#8 Sellers add fix and features
  app/Http/Controllers/Admin/SellerCrudController.php
  app/Models/Seller.php
  app/Observers/SellerObserver.php
  app/Providers/AppServiceProvider.php
  database/migrations/2020_09_24_081051_create_sellers_table.php
  public/js/app.js
  public/js/rut-formatter.js
  resources/views/vendor/backpack/crud/fields/radio_readonly_fields.blade.php
  resources/views/vendor/backpack/crud/fields/readonly_fields_functions.blade.php
Labels: bug, enhancement

#35 Fix seller address
  database/seeds/SellersTableSeeder.php
Labels: bug

#46 Profile: Order view and improvements of profile, addresses and register view
  app/Helpers/helpers.php
  app/Http/Controllers/Frontend/CustomerController.php
  app/Http/Requests/Frontend/CustomerUpdateRequest.php
  app/Models/Customer.php
  resources/views/customer/address.blade.php
  resources/views/customer/order.blade.php
  resources/views/customer/profile.blade.php
  resources/views/customer/sidebar.blade.php
  resources/views/customer/sign.blade.php
  resources/views/vendor/pagination/bootstrap-4.blade.php
Labels: enhancement

#50 Flash messages and temporary fixes
  app/Http/Livewire/Cart/Item.php
  app/Http/Livewire/FlashMessage.php
  app/Http/Livewire/Products/AddToCart.php
  database/migrations/2020_09_30_125808_create_order_items_table.php
  resources/views/livewire/flash-message.blade.php
  resources/views/livewire/products/short-list.blade.php
Labels: bug, documentation, enhancement

#53 complete haveSufficientQuantity function
  app/Models/Product.php
Labels: enhancement

#74 Profile fix modal / Customer reset password
  app/Http/Controllers/Frontend/CustomerController.php
  app/Mail/templates.json
  resources/views/auth/passwords/reset.blade.php
  resources/views/livewire/customer/order-detail.blade.php
  resources/views/vendor/maileclipse/templates/resetPassword.blade.php
  resources/views/vendor/maileclipse/templates/resetPassword_plain_text.blade.php
  routes/web.php
Labels: bug, enhancement

#109 Order products by name, fix category bug
  app/Http/Controllers/Frontend/HomeController.php
  app/Http/Livewire/Products/CardGeneral.php
  app/Models/Product.php
  public/css/theme.css
  resources/views/paginator.blade.php
  resources/views/product.blade.php
  resources/views/shop-grid.blade.php
Labels: bug, enhancement

#118 Remove mail sender
  app/Http/Controllers/Frontend/CustomerController.php
  app/Observers/CustomerObserver.php
Labels: bug

#127 Profile: Use mail templates
  app/Http/Controllers/Frontend/CustomerController.php
  app/Observers/CustomerObserver.php
  resources/views/vendor/maileclipse/templates/passwordChanged.blade.php
  resources/views/vendor/maileclipse/templates/welcomeCustomer.blade.php
Labels: enhancement

#140 Change password if exist in dirty
  app/Models/Seller.php
  app/Observers/SellerObserver.php
Labels: bug
