Repository twgroupcl/simple-gestion, pull requests merged in 2021-02, with the labels that each got.

#424 General fixes prolibro
  app/Http/Controllers/Frontend/HomeController.php
  app/Http/Livewire/Filters.php
  app/Http/Livewire/Products/CardGeneral.php
  app/Models/Product.php
  app/Models/Seller.php
  resources/views/livewire/filters.blade.php
  resources/views/livewire/search-navbar-movile.blade.php
  resources/views/livewire/search-navbar.blade.php
  resources/views/marketplace.blade.php
  resources/views/terms-conditions.blade.php
  resources/views/vendor.blade.php
Labels: bug, enhancement

#432 Fix long text break page on quotation pdf
  resources/views/templates/quotations/export_pdf.blade.php
Labels: bug

#433 Credit note available
  app/Http/Controllers/Admin/ManageInvoiceCrudController.php
  app/Http/Requests/InvoiceRequest.php
  app/Models/Invoice.php
  app/Models/InvoiceType.php
  resources/views/invoice/manage_invoice/actions.blade.php
  resources/views/invoice/manage_invoice/buttons.blade.php
  resources/views/invoice/manage_invoice/issue_credit_note.blade.php
  resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
Labels: bug, question

#446 Add new features to Accounting module
  app/Exports/AccountingAccountExport.php
  app/Exports/TransactionExport.php
  app/Http/Controllers/Admin/AccountingAccountCrudController.php
  app/Http/Controllers/Admin/TransactionCrudController.php
  resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
Labels: bug, enhancement
